Rename second CustomBondForce in HybridTopologyFactory system to have unique name
choderalab/perses pull request #1022
Opened 2022-05-27 19:13 UTC by zhang-ivy

## Description

- Renames second `CustomBondForce` in `HybridTopologyFactory` system to `CustomBondForce_exceptions`
- Updates docstring in `HybridTopologyFactory` to contain the list of forces present in the hybrid system
- Fixes docstring for RESTTopologyFactory to accurately reflect the forces in the system 

## Motivation and context

This change is necessary because https://github.com/choderalab/perses/pull/1007 changes `compute_potential_components()` to use a dictionary where the keys are force names and values are energies.

## How has this been tested?

## Change log

```

```

2022-05-27 21:21 UTC, ijpulidos commented
We also need to change the `validate_endstate_energies_point` because I changed it assuming the bonded forces wouldn't have different names and now it is just broken because we now not only have different names but also different number of components, as far as I can see. 

@zhang-ivy I can contribute code fixing this part once the other parts are completed.

2022-05-27 21:23 UTC, ijpulidos commented
It also makes me realize that we need more testing for this part, because tests should've failed with the previous PR (#1007 ), so we might one to deal with https://github.com/choderalab/perses/issues/1011 at the same time.

2022-05-27 21:31 UTC, ijpulidos commented
> We also need to change the `validate_endstate_energies_point` because I changed it assuming the bonded forces wouldn't have different names and now it is just broken because we now not only have different names but also different number of components, as far as I can see.

@zhang-ivy from our discussion, thanks for pointing out my confusion, we probably don't **need** to change that function, but we might think of better ways of accomplishing what it does without hardcoding forces/components names. Hopefully we can come up with an easy and more robust way, if not, then it's not too bad to leave it as it is.

2022-05-31 17:50 UTC, zhang-ivy commented
@mikemhenry : Also, I think the test failure you linked above is old -- the gpu tests are currently passing.

2022-05-31 20:31 UTC, mikemhenry commented on perses/annihilation/relative.py
> +        name = nonbonded_exceptions_force.__class__.__name__ + '_exceptions'
```suggestion
        name = f"{nonbonded_exceptions_force.__class__.__name__}_exceptions"        
```

2022-05-31 20:32 UTC, mikemhenry requested changes
Just one suggestion!

2022-05-31 22:49 UTC, mikemhenry approved these changes
LGTM

2022-05-31 23:59 UTC, ijpulidos approved these changes
Looks good!

2022-06-01 00:00 UTC, merged