Fix/issue 1196
choderalab/perses pull request #1229
Opened 2023-08-23 18:23 UTC by mikemhenry

## Description
Back ports some fixes from the OpenFE team.

## Motivation and context

Resolves #1196 

## How has this been tested?

## Change log

```

```
Explicitly deleted some sampler and energy contexts in `setup_relative_calculation.py`

2023-08-23 19:06 UTC, ijpulidos requested changes
Seems good, thanks for this! Just a minor change, probably a typo or some accident :)

2023-08-23 19:06 UTC, ijpulidos commented on perses/app/setup_relative_calculation.py
> +        warningg.warn("perses-relative will be removed in 0.11, see https://github.com/choderalab/perses/tree/main/examples/new-cli for new CLI tool", FutureWarning)
Typo? `warningg`

2023-08-23 19:57 UTC, mikemhenry commented on perses/app/setup_relative_calculation.py
> +        warningg.warn("perses-relative will be removed in 0.11, see https://github.com/choderalab/perses/tree/main/examples/new-cli for new CLI tool", FutureWarning)
lmao, yes, I was vim-ing

2023-08-23 19:58 UTC, mikemhenry commented on perses/app/setup_relative_calculation.py
> +        warningg.warn("perses-relative will be removed in 0.11, see https://github.com/choderalab/perses/tree/main/examples/new-cli for new CLI tool", FutureWarning)
```suggestion
        warning.warn("perses-relative will be removed in 0.11, see https://github.com/choderalab/perses/tree/main/examples/new-cli for new CLI tool", FutureWarning)
```

2023-08-25 05:32 UTC, ijpulidos approved these changes
LGTM!

2023-08-25 06:05 UTC, merged